### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by beyaz** [Alpzy/Focus-Dimmer#1]
Çok faydalı bir çalışma olmuş tebrik ediyorum.
Visual studio 2017  'yi de desteklemeyi düşünüyor musunuz ?

**Comment by Alpzy** [comment]
Öncelikle teşekkürler. Sorunuzun cevabına gelince; şimdilik hayır, böyle bir niyetim yok. Konu ile ilgili çalışmanız olursa paylaşmaktan çekinmeyin lütfen. :)
